version: 2.1

orbs:
  branch-management: opennms/branch-management@2.3.0

commands:
  restore-node-cache:
    steps:
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-v1-{{ .Branch }}
            - npm-cache-v1-
  save-node-cache:
    steps:
      - save_cache:
          name: Save Package Cache
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
  build-dist:
    steps:
      - restore-node-cache
      - run:
          name: Install Dependencies
          command: npm ci
      - save-node-cache
      - run:
          name: Run dist build
          no_output_timeout: 20m
          command: npm run full
  build-merge:
    steps:
      - restore-node-cache
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run merge build
          no_output_timeout: 20m
          command: npm run merge

jobs:
  build:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - build-dist
      - run:
          name: pack API documentation
          command: |
            pushd dist/docs
            zip -9 -r ../../build/api.zip .
      - store_artifacts:
          path: build/api.zip
          destination: api-docs.zip
  build-docs:
    docker:
      - image: opennms/antora:3.1.4-b10433
    steps:
      - checkout
      - run:
          name: Validate Xrefs in docs
          command: |
            NODE_PATH="$(npm -g root)" antora --generator @antora/xref-validator local-site.yml
      - run:
          name: Build docs with Antora
          command: |
             NODE_PATH="$(npm -g root)" antora --stacktrace generate local-site.yml
      - store_artifacts:
          path: build/site.zip
          destination: antora-docs.zip
  merge:
    docker:
      - image: cimg/node:20.19
    steps:
      #- add_ssh_keys:
      #    fingerprints:
      #      - "82:76:19:fb:6a:71:a3:c5:cf:7c:99:aa:82:45:4a:96"
      - checkout
      - branch-management/merge-branch:
          committer_email: "cicd-system@opennms.com"
          committer_name: "CI/CD System"
          from: develop
          to: main
      - build-merge
      - run:
          name: "Commit Changes"
          command: |
            export GIT_MERGE_AUTOEDIT=no
            git add -A --force dist
            git commit -a --no-verify -m "autogenerated runtime build artifacts"
      - run:
          name: "Push to Main"
          command: git push --no-verify origin main:main
  pages:
    docker:
      - image: cimg/node:20.19
    steps:
      #- add_ssh_keys:
      #    fingerprints:
      #      - "82:76:19:fb:6a:71:a3:c5:cf:7c:99:aa:82:45:4a:96"
      - checkout
      - branch-management/merge-branch:
          committer_email: "cicd-system@opennms.com"
          committer_name: "CI/CD System"
          from: main
          to: gh-pages
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-v1-{{ .Branch }}
            - npm-cache-v1-
      - run:
          name: "Publish API Docs to docs/"
          command: |
            export GIT_MERGE_AUTOEDIT=no
            npm ci
            npm run api
            rm -rf docs/*
            cp -pR dist/docs/* docs/
            git add -A docs
            git commit --author='CI/CD System <cicd-system@opennms.com>' -m 'publish latest API docs'
      - run:
          name: "Push to GitHub Pages"
          command: git push --no-verify origin gh-pages:gh-pages


workflows:
  build-and-merge:
    jobs:
      - build
      - build-docs
      - merge:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - pages:
          requires:
            - build
          filters:
            branches:
              only:
                - main
